spring.datasource.url=${DB_URL}
spring.datasource.username=admin
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8090

spring.security.user.name=admin
spring.security.user.password=${DB_ADMIN_PASSWORD}

JWT_SECRET=${JWT_SECRET}
